apiVersion: v1
kind: Service
metadata:
  name: quotes-svc
  labels:
    app: quotes-api
spec:
  type: NodePort
  selector:
    app: quotes-api
  ports:
    - port: 80
      targetPort: 8000
      nodePort: 30080
      protocol: TCP
